Fixes
Maua-Dev/clean_mss_template pull request #19
Opened 2023-06-26 19:42 UTC by Lucasdvs10

Mudanças que o Soller me pediu para fazer

2023-06-27 10:48 UTC, VgsStudio requested changes

2023-06-27 10:48 UTC, VgsStudio commented on iac/app.py
> +TemplateStack(app,"Test-Observability", stack_name=stack_name, tags=tags, env={'region': os.environ.get("REGION")})
esse env= ta errado, eu acho

https://github.com/Maua-Dev/mf_mss_product/blob/dev/iac/app.py

2023-06-27 10:48 UTC, VgsStudio commented on src/shared/environments.py
> -            self.dynamo_table_name = "user_mss_template-table"
vc copiu da smile o arquivo, mas não inteiro. (não copiou a parte do STAGE onde tinha o HOMOLOG.
volta o arquivo anterior (pega no git) e copia da smile só onde consta a palavra HOMOLOG. Ela aparece na hora de definir o stage e na hora de escolhei qual repo vai ser utilizado.

2023-06-27 10:48 UTC, VgsStudio commented on src/shared/infra/external/dynamo/datasources/dynamo_datasource.py
> +        while 'LastEvaluatedKey' in resp:
perfeito, era isso mesmo que queria que arrumasse. pra vc ter noção, isso aqui diminuiu o tempo de resposta em 4 segundos.

esse bloco de códig que eu marquei é a única coisa que me preocupa, falei com o rodrigo pra ele arrumar com multithreading, ele disse que ia falar com vcs pra aprenderem e *tentarem* resolver. aqui ta tudo ótimo, n precisa mudar

2023-06-27 10:48 UTC, VgsStudio commented on src/shared/infra/external/dynamo/datasources/dynamo_datasource.py
> -    dynamo.update_item("student#21002088", "21002088", {"name": "Maluzinha", "ra": "21002088"})
F

2023-06-28 12:41 UTC, Lucasdvs10 commented on iac/app.py
> +TemplateStack(app,"Test-Observability", stack_name=stack_name, tags=tags, env={'region': os.environ.get("REGION")})
Deixei igual ao do mauá food

2023-06-28 12:43 UTC, Lucasdvs10 commented on src/shared/environments.py
> -            self.dynamo_table_name = "user_mss_template-table"
Voltei o arquivo e copiei o Stage e as linhas que citavam o Homolog, vê se agr tá certin

2023-06-28 12:44 UTC, Lucasdvs10 commented on src/shared/infra/external/dynamo/datasources/dynamo_datasource.py
> -    dynamo.update_item("student#21002088", "21002088", {"name": "Maluzinha", "ra": "21002088"})
F total

2023-06-28 12:45 UTC, Lucasdvs10 commented on src/shared/infra/external/dynamo/datasources/dynamo_datasource.py
> +        while 'LastEvaluatedKey' in resp:
Meeeu deeeus

Po, se a gente conseguir fazer multithreading bonitinho, vai dar pra diminuir legal

2023-06-28 14:10 UTC, VgsStudio approved these changes

2023-06-28 14:10 UTC, VgsStudio commented on iac/app.py
> +TemplateStack(app,"Test-Observability", stack_name=stack_name, env=cdk.Environment(account=aws_account_id, region=aws_region), tags=tags)
O stack name é o nome que vai aparecer na AWS quando a gente dar deploy, para deixar de forma genérica, baseada no nome da branch, a gente montou um CD que conforme o ambiente, ele da um nome diferente pro stack, pra gente conseguir testar as funcionaldiades. Aquele "Test-Observability" é o nome do stack, mas vc passou tbm o stack_name=stack_name. Tira a String hardcodada do "Test-Observability".

2023-06-28 14:10 UTC, VgsStudio commented on src/shared/environments.py
> +    HOMOLOG = "HOMOLOG"
otimo era isso que eu queia mesmo

2023-06-28 14:10 UTC, VgsStudio commented on src/shared/environments.py
> +        elif Environments.get_envs().stage in [STAGE.DEV, STAGE.HOMOLOG, STAGE.PROD]:
otimo, otimo. ai conforme o stage a gente da deploy num repo diferente

2023-06-28 14:10 UTC, VgsStudio commented on src/shared/environments.py
> +        elif Environments.get_envs().stage in [STAGE.DEV, STAGE.HOMOLOG, STAGE.PROD]:
mas vai nesse mesmo arquivo, na linhda 69 e coloca esse mesmo if la 
![image](https://github.com/Maua-Dev/clean_mss_template/assets/81604963/ffcda970-4efa-4400-a3a8-7ce2f45fd3b1)

pq ai independente do stage ele da deploy no repo dynamo, saca?

2023-06-29 13:23 UTC, Lucasdvs10 commented on iac/app.py
> +TemplateStack(app,"Test-Observability", stack_name=stack_name, env=cdk.Environment(account=aws_account_id, region=aws_region), tags=tags)
Prontin

2023-06-29 13:25 UTC, Lucasdvs10 commented on src/shared/environments.py
> +        elif Environments.get_envs().stage in [STAGE.DEV, STAGE.HOMOLOG, STAGE.PROD]:
Prontin

2023-06-29 13:34 UTC, VgsStudio approved these changes

2023-06-29 13:45 UTC, merged